id: AB85F550B
title: Toh_142-The_Dharani_Entering_into_Non-conceptuality-v2
type: translation
pechas:
- I4B45ABE0
- IB22A0904
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-001
  eft-text-version: 1.1.5 2020
  title: Toh_142-The_Dharani_Entering_into_Non-conceptuality-v2
alignment_to_base:
  I4B45ABE0/490E: 8BD0
  IB22A0904/72CA: 8BD0
